API_keys: # Do not share this information
    public: sviVil27kXqEMp6X1xaHCa0C8F1GkIea09QVkL4Mg4Rm4a6CgxXobTd50qXprBQA
    private: Ho0eAkaMmS8DCeKg9X8cOfSPdwNoN3E3ITFzmToD3dK2Zqpkas7hRtrNWnAXTDhN
connection_settings:
    target_cryptos: # Add more crypto symbols if you want.
        - BTCUSDT
    first_time: yes #If yes then we populate with data from the last 6 months.
    resolution: 1m  #we get the data minute by minute. If first_time is yes
    units: month    #we are going to insert data offline using months units. If first_time is yes
    num_of_units: 6 # we want to insert data from now to 6 months ago. If first_time is yes
  
